"""Initial migration - all tables

Revision ID: 87418c357f8c
Revises: 
Create Date: 2025-06-28 16:56:40.828469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87418c357f8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('control_tokens', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'owner_id', name='uq_world_name_owner')
    )
    op.create_index('idx_world_owner_name', 'worlds', ['owner_id', 'name'], unique=False)
    op.create_index(op.f('ix_worlds_name'), 'worlds', ['name'], unique=False)
    op.create_index(op.f('ix_worlds_owner_id'), 'worlds', ['owner_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('openness', sa.Float(), nullable=False),
    sa.Column('conscientiousness', sa.Float(), nullable=False),
    sa.Column('extraversion', sa.Float(), nullable=False),
    sa.Column('agreeableness', sa.Float(), nullable=False),
    sa.Column('neuroticism', sa.Float(), nullable=False),
    sa.Column('core_data_json', sa.JSON(), nullable=True),
    sa.Column('imports_data', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('agreeableness >= 0 AND agreeableness <= 1', name='ck_agreeableness_range'),
    sa.CheckConstraint('conscientiousness >= 0 AND conscientiousness <= 1', name='ck_conscientiousness_range'),
    sa.CheckConstraint('extraversion >= 0 AND extraversion <= 1', name='ck_extraversion_range'),
    sa.CheckConstraint('neuroticism >= 0 AND neuroticism <= 1', name='ck_neuroticism_range'),
    sa.CheckConstraint('openness >= 0 AND openness <= 1', name='ck_openness_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'world_id', name='uq_character_name_world')
    )
    op.create_index('idx_character_world_owner', 'characters', ['world_id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    op.create_index(op.f('ix_characters_world_id'), 'characters', ['world_id'], unique=False)
    op.create_table('world_factions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeline_events', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'name', name='uq_world_faction_name')
    )
    op.create_index(op.f('ix_world_factions_world_id'), 'world_factions', ['world_id'], unique=False)
    op.create_table('world_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_world_fact_key')
    )
    op.create_index(op.f('ix_world_facts_world_id'), 'world_facts', ['world_id'], unique=False)
    op.create_table('world_places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'name', name='uq_world_place_name')
    )
    op.create_index(op.f('ix_world_places_world_id'), 'world_places', ['world_id'], unique=False)
    op.create_table('world_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_world_timeline_year', 'world_timeline', ['world_id', 'year'], unique=False)
    op.create_index(op.f('ix_world_timeline_world_id'), 'world_timeline', ['world_id'], unique=False)
    op.create_table('character_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_goals_character_id'), 'character_goals', ['character_id'], unique=False)
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('affinity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('affinity >= -10 AND affinity <= 10', name='ck_affinity_range'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'name', name='uq_character_relationship_name')
    )
    op.create_index(op.f('ix_character_relationships_character_id'), 'character_relationships', ['character_id'], unique=False)
    op.create_table('character_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'tag', name='uq_character_tag')
    )
    op.create_index('idx_character_tag_value', 'character_tags', ['tag'], unique=False)
    op.create_index(op.f('ix_character_tags_character_id'), 'character_tags', ['character_id'], unique=False)
    op.create_table('preference_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('chosen_text', sa.Text(), nullable=False),
    sa.Column('rejected_json', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preference_character_created', 'preference_pairs', ['character_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_preference_pairs_character_id'), 'preference_pairs', ['character_id'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('base_model', sa.String(length=200), nullable=False),
    sa.Column('training_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sft_adapter_path', sa.String(length=500), nullable=True),
    sa.Column('rlhf_adapter_path', sa.String(length=500), nullable=True),
    sa.Column('output_directory', sa.String(length=500), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('final_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_run_character_status', 'training_runs', ['character_id', 'status'], unique=False)
    op.create_index('idx_training_run_status', 'training_runs', ['status'], unique=False)
    op.create_index(op.f('ix_training_runs_character_id'), 'training_runs', ['character_id'], unique=False)
    op.create_index(op.f('ix_training_runs_owner_id'), 'training_runs', ['owner_id'], unique=False)
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_random', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['world_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_events_place_id'), 'world_events', ['place_id'], unique=False)
    op.create_table('world_npcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['world_places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_npcs_place_id'), 'world_npcs', ['place_id'], unique=False)
    op.drop_index('idx_character_ratings_character', table_name='character_ratings')
    op.drop_table('character_ratings')
    op.drop_table('session_characters')
    op.drop_table('character_stats')
    op.drop_index('idx_published_worlds_creator', table_name='published_worlds')
    op.drop_index('idx_published_worlds_featured', table_name='published_worlds')
    op.drop_table('published_worlds')
    op.drop_index('idx_play_sessions_user', table_name='play_sessions')
    op.drop_index('idx_play_sessions_world', table_name='play_sessions')
    op.drop_table('play_sessions')
    op.drop_table('world_stats')
    op.drop_index('idx_world_ratings_world', table_name='world_ratings')
    op.drop_table('world_ratings')
    op.drop_index('idx_published_characters_creator', table_name='published_characters')
    op.drop_index('idx_published_characters_world', table_name='published_characters')
    op.drop_table('published_characters')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.create_table('published_characters',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('world_id', sa.INTEGER(), nullable=False),
    sa.Column('character_name', sa.TEXT(), nullable=False),
    sa.Column('creator_user_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tags', sa.TEXT(), nullable=False),
    sa.Column('character_data', sa.TEXT(), nullable=True),
    sa.Column('published_at', sa.TEXT(), nullable=False),
    sa.Column('featured', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['published_worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'character_name')
    )
    op.create_index('idx_published_characters_world', 'published_characters', ['world_id'], unique=False)
    op.create_index('idx_published_characters_creator', 'published_characters', ['creator_user_id'], unique=False)
    op.create_table('world_ratings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('world_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['published_worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'user_id')
    )
    op.create_index('idx_world_ratings_world', 'world_ratings', ['world_id'], unique=False)
    op.create_table('world_stats',
    sa.Column('world_id', sa.INTEGER(), nullable=True),
    sa.Column('total_sessions', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('active_sessions', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_session_duration', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('total_ratings', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_rating', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('last_updated', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['published_worlds.id'], ),
    sa.PrimaryKeyConstraint('world_id')
    )
    op.create_table('play_sessions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('world_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_name', sa.TEXT(), nullable=False),
    sa.Column('privacy_setting', sa.TEXT(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'setup'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('last_active', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['published_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_play_sessions_world', 'play_sessions', ['world_id'], unique=False)
    op.create_index('idx_play_sessions_user', 'play_sessions', ['user_id'], unique=False)
    op.create_table('published_worlds',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('world_name', sa.TEXT(), nullable=False),
    sa.Column('creator_user_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tags', sa.TEXT(), nullable=False),
    sa.Column('thumbnail_url', sa.TEXT(), nullable=True),
    sa.Column('published_at', sa.TEXT(), nullable=False),
    sa.Column('featured', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_name')
    )
    op.create_index('idx_published_worlds_featured', 'published_worlds', ['featured'], unique=False)
    op.create_index('idx_published_worlds_creator', 'published_worlds', ['creator_user_id'], unique=False)
    op.create_table('character_stats',
    sa.Column('character_id', sa.INTEGER(), nullable=True),
    sa.Column('download_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('session_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('interaction_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_ratings', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_rating', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('last_updated', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['published_characters.id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('session_characters',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('character_name', sa.TEXT(), nullable=False),
    sa.Column('character_data', sa.TEXT(), nullable=True),
    sa.Column('added_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['play_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_ratings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('review_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5'),
    sa.ForeignKeyConstraint(['character_id'], ['published_characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'user_id')
    )
    op.create_index('idx_character_ratings_character', 'character_ratings', ['character_id'], unique=False)
    op.drop_index(op.f('ix_world_npcs_place_id'), table_name='world_npcs')
    op.drop_table('world_npcs')
    op.drop_index(op.f('ix_world_events_place_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_training_runs_owner_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_character_id'), table_name='training_runs')
    op.drop_index('idx_training_run_status', table_name='training_runs')
    op.drop_index('idx_training_run_character_status', table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_index(op.f('ix_preference_pairs_character_id'), table_name='preference_pairs')
    op.drop_index('idx_preference_character_created', table_name='preference_pairs')
    op.drop_table('preference_pairs')
    op.drop_index(op.f('ix_character_tags_character_id'), table_name='character_tags')
    op.drop_index('idx_character_tag_value', table_name='character_tags')
    op.drop_table('character_tags')
    op.drop_index(op.f('ix_character_relationships_character_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_character_goals_character_id'), table_name='character_goals')
    op.drop_table('character_goals')
    op.drop_index(op.f('ix_world_timeline_world_id'), table_name='world_timeline')
    op.drop_index('idx_world_timeline_year', table_name='world_timeline')
    op.drop_table('world_timeline')
    op.drop_index(op.f('ix_world_places_world_id'), table_name='world_places')
    op.drop_table('world_places')
    op.drop_index(op.f('ix_world_facts_world_id'), table_name='world_facts')
    op.drop_table('world_facts')
    op.drop_index(op.f('ix_world_factions_world_id'), table_name='world_factions')
    op.drop_table('world_factions')
    op.drop_index(op.f('ix_characters_world_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index('idx_character_world_owner', table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_worlds_owner_id'), table_name='worlds')
    op.drop_index(op.f('ix_worlds_name'), table_name='worlds')
    op.drop_index('idx_world_owner_name', table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_table('database_version')
    # ### end Alembic commands ###
